### ISSUE TITLE
Have a collection of slideshows, will it help?

### ISSUE THREAD

**Issue by PrashamTrivedi** [AndroidStudyGroup/conferences#28]
I have a collection of (bit older) slideshows. Which is [here](http://prashamtrivedi.github.io/Slideshows/) with [yml file](https://github.com/PrashamTrivedi/PrashamTrivedi.github.io/blob/master/_data/slideshows.yml)

If it helps, I am open to create a pull request.

**Comment by chiuki** [comment]
Nice! Yes, it'll be useful to have it.

### The easy way (wiki)

Link from the wiki: https://github.com/AndroidStudyGroup/conferences/wiki

### The not-too-hard way (wiki)
1. Create individual pages in the wiki for each conference (just like [DroidconNYC2015](https://github.com/AndroidStudyGroup/conferences/wiki/DroidconNYC2015)).
2. Copy the links over.

### The hard way (jekyll)
1. Add the individual conferences.
2. Add a field to link to slides. You'll need to add targets to your page or split out each conference onto its own page.
3. Add tab on [jekyll main page](http://androidstudygroup.github.io/conferences/) to show past conferences.

I don't have a preference so pick the option you like :smile:

**Comment by PrashamTrivedi** [comment]
I am open for all three and eventually do all.

For my collection I did not follow the format shown in wiki. I only have
slideshow name and link. For authors I have names and (mostly) Google+
profile links. Please tell me if this format is needs a change.

**Comment by chiuki** [comment]
Yes, your format is fine. Thanks!

**Comment by JakeWharton** [comment]
Let's prefer the wiki for this, since it's what we're already using.
