### ISSUE TITLE
The website is not getting updated

### ISSUE THREAD

**Issue by davidvavra** [AndroidStudyGroup/conferences#352]
I don't see my last merged conference (mDevCamp) on the website. I checked the CI and the log looks OK, anybody knows what's wrong?

**Comment by ifeomaro** [comment]
Hey @davidvavra, it looks like [mdevcamp_2018.md](https://raw.githubusercontent.com/AndroidStudyGroup/conferences/gh-pages/_conferences/mdevcamp_2018.md) is missing the 3 dashes on the top and bottom of the file as is shown in [addc-2018.md](https://raw.githubusercontent.com/AndroidStudyGroup/conferences/gh-pages/_conferences/addc-2018.md).

**Comment by davidvavra** [comment]
Thanks!
