### ISSUE TITLE
Past conferences shown in Upcoming

### ISSUE THREAD

**Issue by Egorand** [AndroidStudyGroup/conferences#372]
At the moment, the first 3 conferences in the Upcoming tab are:

2018-03-12  MobileTech Conference  Munich, Germany
2018-03-15  AppDevCon  Amsterdam, NL
2018-03-26  Droidcon  Boston, MA, USA

The former 2 are already over, so they shouldn't appear here.

**Comment by JakeWharton** [comment]
It's a static site so it only updates when something changes.

**Comment by Egorand** [comment]
Oh, I see, it's confusing. Feel free to close though if no plans to fix this.

**Comment by JakeWharton** [comment]
We can filter them out with JS.

**Comment by cketti** [comment]
Maybe display them using a lighter text color? If we hide them they're gone until the next update when they reappear on the "Past" page.

**Comment by JakeWharton** [comment]
Sure!
